name: "Label Issue"
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.2
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          enable-versioned-regex: 1
          versioned-regex: 'issue_labeler_regex_version=(\d+)'
